"""empresa aliquota_extra

Revision ID: 6fc25d6fe9fa
Revises: fd4f605e1cfb
Create Date: 2026-07-14 14:08:18.070199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6fc25d6fe9fa'
down_revision: Union[str, None] = 'fd4f605e1cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'empresa',
        sa.Column('aliquota_extra', sa.Numeric(precision=6, scale=3), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'aliquota_extra')
    # ### end Alembic commands ###
