"""modulo precificacao

Revision ID: af2e3dffe6ea
Revises: 49c18732e976
Create Date: 2026-07-16 21:33:46.579765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'af2e3dffe6ea'
down_revision: Union[str, None] = '49c18732e976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componente_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('por_pedido', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('custo_base', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('montagem_por_chapa', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabela_aliquota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(length=60), nullable=False),
    sa.Column('aliquota', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('regime', sa.String(length=10), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local')
    )
    op.create_table('tabela_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acabamento', sa.String(length=30), nullable=False),
    sa.Column('quantidade_min', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acabamento', 'quantidade_min', name='uq_label_acab_faixa')
    )
    op.create_table('orcamento_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('empresa_faturamento_id', sa.Integer(), nullable=True),
    sa.Column('condicao_pagamento_dias', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('criado_por', sa.String(length=80), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_faturamento_id'], ['empresa.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametro_precificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('margem_padrao', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('comissao_padrao', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('custo_fixo_padrao', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('juros_mes', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('prazo_padrao', sa.Integer(), nullable=False),
    sa.Column('perda_label', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', name='uq_parametro_empresa')
    )
    op.create_table('item_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('acabamento', sa.String(length=30), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento_venda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_orcamento_orcamento_id'), 'item_orcamento', ['orcamento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_orcamento_orcamento_id'), table_name='item_orcamento')
    op.drop_table('item_orcamento')
    op.drop_table('parametro_precificacao')
    op.drop_table('orcamento_venda')
    op.drop_table('tabela_label')
    op.drop_table('tabela_aliquota')
    op.drop_table('produto')
    op.drop_table('componente_custo')
    # ### end Alembic commands ###
