"""horizontes 1 e 2

Revision ID: cd5697e1341f
Revises: 6fc25d6fe9fa
Create Date: 2026-07-15 00:06:40.265997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cd5697e1341f'
down_revision: Union[str, None] = '6fc25d6fe9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_projeto', sa.String(length=80), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentario_chave_projeto'), 'comentario', ['chave_projeto'], unique=False)
    op.create_table('configuracao',
    sa.Column('chave', sa.String(length=40), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('fechamento_aprovado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_projeto', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('periodo_de', sa.Date(), nullable=True),
    sa.Column('periodo_ate', sa.Date(), nullable=True),
    sa.Column('dados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fechamento_aprovado_chave_projeto'), 'fechamento_aprovado', ['chave_projeto'], unique=False)
    op.create_table('orcamento',
    sa.Column('chave_projeto', sa.String(length=80), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=120), nullable=False),
    sa.Column('receita_prevista', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('custo_previsto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('atualizado_por', sa.String(length=80), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chave_projeto')
    )
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_omie', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_omie', name='uq_vendedor_empresa_codigo')
    )
    op.add_column('titulo', sa.Column('codigo_vendedor', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titulo', 'codigo_vendedor')
    op.drop_table('vendedor')
    op.drop_table('orcamento')
    op.drop_index(op.f('ix_fechamento_aprovado_chave_projeto'), table_name='fechamento_aprovado')
    op.drop_table('fechamento_aprovado')
    op.drop_table('configuracao')
    op.drop_index(op.f('ix_comentario_chave_projeto'), table_name='comentario')
    op.drop_table('comentario')
    # ### end Alembic commands ###
