"""schema inicial

Revision ID: fd4f605e1cfb
Revises: 
Create Date: 2026-07-13 15:57:10.344144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fd4f605e1cfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('app_key_enc', sa.Text(), nullable=False),
    sa.Column('app_secret_enc', sa.Text(), nullable=False),
    sa.Column('regime', sa.String(length=10), nullable=False),
    sa.Column('simples_anexo', sa.String(length=3), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ajuste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=10), nullable=False),
    sa.Column('alvo_id', sa.BigInteger(), nullable=False),
    sa.Column('campo', sa.String(length=30), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=False),
    sa.Column('valor_novo', sa.Text(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_categoria', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('grupo', sa.String(length=12), nullable=True),
    sa.Column('atualizado_por', sa.String(length=80), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_categoria', name='uq_catgrupo_empresa_cat')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_cliente_omie', sa.BigInteger(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj_cpf', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_cliente_omie', name='uq_cliente_empresa_codigo')
    )
    op.create_table('nfe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('id_nf', sa.BigInteger(), nullable=False),
    sa.Column('n_nf', sa.String(length=15), nullable=False),
    sa.Column('serie', sa.String(length=5), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('d_emi', sa.Date(), nullable=True),
    sa.Column('tp_nf', sa.String(length=1), nullable=False),
    sa.Column('cancelada', sa.Boolean(), nullable=False),
    sa.Column('id_pedido', sa.BigInteger(), nullable=True),
    sa.Column('codigo_projeto_omie', sa.BigInteger(), nullable=True),
    sa.Column('dest_nome', sa.String(length=120), nullable=False),
    sa.Column('dest_cnpj', sa.String(length=20), nullable=False),
    sa.Column('v_nf', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_prod', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_icms', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_st', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_fcp', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_fcpst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_ipi', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_pis', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_cofins', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_ibs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('v_cbs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('titulos', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'id_nf', name='uq_nfe_empresa_idnf')
    )
    op.create_index('ix_nfe_empresa_emissao', 'nfe', ['empresa_id', 'd_emi'], unique=False)
    op.create_index('ix_nfe_empresa_projeto', 'nfe', ['empresa_id', 'codigo_projeto_omie'], unique=False)
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_omie', sa.BigInteger(), nullable=False),
    sa.Column('cod_int', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('inativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_omie', name='uq_projeto_empresa_codigo')
    )
    op.create_table('simples_periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('rbt12', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'competencia', name='uq_simples_empresa_comp')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('recurso', sa.String(length=30), nullable=False),
    sa.Column('periodo_de', sa.Date(), nullable=True),
    sa.Column('periodo_ate', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qtd_registros', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=8), nullable=False),
    sa.Column('codigo_lancamento_omie', sa.BigInteger(), nullable=False),
    sa.Column('codigo_projeto_omie', sa.BigInteger(), nullable=True),
    sa.Column('valor_documento', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('codigo_categoria', sa.String(length=40), nullable=False),
    sa.Column('categorias_rateio', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('status_titulo', sa.String(length=30), nullable=False),
    sa.Column('codigo_cliente_fornecedor', sa.BigInteger(), nullable=True),
    sa.Column('numero_documento', sa.String(length=60), nullable=False),
    sa.Column('numero_documento_fiscal', sa.String(length=60), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo', 'codigo_lancamento_omie', name='uq_titulo_empresa_tipo_cod')
    )
    op.create_index('ix_titulo_empresa_emissao', 'titulo', ['empresa_id', 'data_emissao'], unique=False)
    op.create_index('ix_titulo_empresa_projeto', 'titulo', ['empresa_id', 'codigo_projeto_omie'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_titulo_empresa_projeto', table_name='titulo')
    op.drop_index('ix_titulo_empresa_emissao', table_name='titulo')
    op.drop_table('titulo')
    op.drop_table('sync_log')
    op.drop_table('simples_periodo')
    op.drop_table('projeto')
    op.drop_index('ix_nfe_empresa_projeto', table_name='nfe')
    op.drop_index('ix_nfe_empresa_emissao', table_name='nfe')
    op.drop_table('nfe')
    op.drop_table('cliente')
    op.drop_table('categoria_grupo')
    op.drop_table('ajuste')
    op.drop_table('empresa')
    # ### end Alembic commands ###
